### ISSUE TITLE
Simple example raise "NameError" exception

### ISSUE THREAD

**Issue by arslogavitabrevis** [BondGraphTools/BondGraphTools#135]
In the simple example provided in _init_.py, "bgt." is missing before the connect functions and the simulate function. This  applied to the lines 41 to 47 in _init_.py. This cause a NameError when running the example.

**Comment by arslogavitabrevis** [comment]
This "bgt." is also missing in the "Tutorial: Driven Filter Circuit" in readthedocs.io.

**Comment by peter-cudmore** [comment]
Should be fixed in version 0.4
