### ISSUE TITLE
Unable to connect components with multiple port (like GY of TF)

### ISSUE THREAD

**Issue by arslogavitabrevis** [BondGraphTools/BondGraphTools#136]
I was unable to connect a component of type GY or TF. 

I was able to fix the problem by adding a condition "and not isinstance(port,int)" in the if of the method get_port of the PortExpander class (in the file port_manager.py). 
I also added a condition in the _find_or_make_port function in the "action.py" file:
if component.metamodel == 'TF' or component.metamodel == 'GY':
            if is_tail:
                p = component.get_port(0)
            else:
                p = component.get_port(1)

I think my solution is only a fix, the problem will beback with other multiport component.

**Comment by peter-cudmore** [comment]
when you connect to a transformer or gyratyor, you need to specify which port.
For example, in an electrical transformer, there is a primary and secondary winding, similar concepts apply to gear boxes. 
If we take `j` to be a junction, and `tf` to be a transformer component,
Use `connect(j, (tf, 0))` to connect to the primary winding

**Comment by arslogavitabrevis** [comment]
Thanks your for the explanation that makes good sense. From this explanation, maybe I could produce small example for tf or gy usage for unexperienced user like me.
