### ISSUE TITLE
The function simulate take a ndarray as an input for x0 but not for dx0

### ISSUE THREAD

**Issue by arslogavitabrevis** [BondGraphTools/BondGraphTools#137]
When  I use an ndArray for dx0 parameter for the function simulate, I get an error.

  File "C:\Program Files\Python36\lib\site-packages\BondGraphTools\sim_tools.py", line 35, in _fetch_ic
    if dx0:
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

**Comment by peter-cudmore** [comment]
This is a bug. 

However, is it physically reasonable to want to specify `dx_0`? 
If not, then this argument should be removed

**Comment by arslogavitabrevis** [comment]
I used your library for a problem with a changing inertia. I ran the simulation multiple time on small increment of time and used the previous dx_0 as the input of the next simulation.

**Comment by peter-cudmore** [comment]
This has been implemented in 0.4.3.
