### ISSUE TITLE
following tutorial 1,  I got an error report

### ISSUE THREAD

**Issue by Conearth** [BondGraphTools/BondGraphTools#145]
with code "**t, x = simulate(model, timespan=timespan, x0=x0, control_vars={'u_0':2})**"

I got an error report:

File "D:\Program Files\Anaconda3\envs\BGT\lib\site-packages\BondGraphTools\sim_tools.py", line 190, in _bondgraph_to_residuals
    raise ModelException(message)
BondGraphTools.exceptions.ModelException: Invalid control function for var: 0.
 Control functions should be of the form:
0 = f(t, x, dx/dt)

**Thank you very much for attention!**

**Comment by Conearth** [comment]
### **full report:**
Traceback (most recent call last):
  File "D:\Program Files\Anaconda3\envs\BGT\lib\site-packages\BondGraphTools\sim_tools.py", line 180, in _bondgraph_to_residuals
    r = f(0, 0, 0)
TypeError: 'int' object is not callable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:/学习/BondGraphTest/test.py", line 36, in <module>
    t, x = simulate(model, timespan=timespan, x0=x0, control_vars=[2,2])
  File "D:\Program Files\Anaconda3\envs\BGT\lib\site-packages\BondGraphTools\sim_tools.py", line 122, in simulate
    res, X = _bondgraph_to_residuals(system, control_vars)
  File "D:\Program Files\Anaconda3\envs\BGT\lib\site-packages\BondGraphTools\sim_tools.py", line 190, in _bondgraph_to_residuals
    raise ModelException(message)
BondGraphTools.exceptions.ModelException: Invalid control function for var: 0.
 Control functions should be of the form:
0 = f(t, x, dx/dt)

**Comment by gdmcbain** [comment]
I just hit the same.

I can fix it here and obtain the expected evolution by replacing 2 with `lambda _, __, ___: 2`; i.e.
```python
t, x = bgt.simulate(model, timespan=timespan, x0=x0, control_vars={"u_0": lambda _, __, ___: 2})
```

I'd propose a PR for the docs but I'm very new to BondGraphTools (maybe ten minutes) so expect there's a more idiomatic way to express constant effort.

**Comment by gdmcbain** [comment]
Oh, I see, following on to the next step of the tutorial with the sinusoidal forcing, I see that a string will do:
```python
t, x = bgt.simulate(model, timespan=timespan, x0=x0, control_vars={"u_0": "2"})
```

**Comment by peter-cudmore** [comment]
@Conearth and @gdmcbain

There was a issue with read-the-docs not building the v0.4 release.
This is now fixed, and the tutorials are now showing the correct thing.

Please let me know if you still have issues.
Cheers
